/**
 * Generates src/message-keys.ts: a string-literal union of every message key
 * in messages/en.json (the reference catalog). A typo in a key then fails
 * compilation in every app instead of rendering "[missing]" at runtime.
 *
 * Usage: node scripts/generate-keys.mjs
 */
import { readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const en = JSON.parse(readFileSync(resolve(root, 'messages/en.json'), 'utf8'));

const flatten = (obj, prefix = '') =>
  Object.entries(obj).flatMap(([key, value]) => {
    const path = prefix ? `${prefix}.${key}` : key;
    return typeof value === 'object' && value !== null ? flatten(value, path) : [path];
  });

const keys = flatten(en).sort();

const header = '// AUTO-GENERATED by scripts/generate-keys.mjs — do not edit by hand.';
const body = `export type MessageKey =\n${keys.map((k) => `  | '${k}'`).join('\n')};\n\nexport const MESSAGE_KEYS = [\n${keys.map((k) => `  '${k}',`).join('\n')}\n] as const;\n`;

writeFileSync(resolve(root, 'src/message-keys.ts'), `${header}\n${body}`);
console.log(`generated src/message-keys.ts with ${keys.length} keys`);
