/**
 * Emits app/theme.generated.css: one CSS custom property per value exported by
 * @dnc/tokens. It is the ONLY place a raw token value may enter the web app —
 * globals.css derives every semantic colour from these variables, so a token
 * change is a single edit in packages/tokens plus a re-run of this script.
 *
 * The package is imported by relative path rather than by its name because Node
 * refuses to type-strip TypeScript resolved inside node_modules.
 *
 * Usage: node scripts/generate-theme.mjs
 */
import { writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';

const here = dirname(fileURLToPath(import.meta.url));
const tokens = await import(resolve(here, '../../../packages/tokens/src/index.ts'));

/** camelCase -> kebab-case, so `surfaceMuted` becomes `--dnc-color-surface-muted`. */
const kebab = (name) => name.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

const lines = [];
const push = (heading, entries) => {
  lines.push(`  /* ${heading} */`);
  for (const [name, value] of entries) lines.push(`  ${name}: ${value};`);
  lines.push('');
};

push(
  'colors',
  Object.entries(tokens.colors).map(([k, v]) => [`--dnc-color-${kebab(k)}`, v]),
);
push(
  'spacing (px on a 4px base grid)',
  Object.entries(tokens.spacing).map(([k, v]) => [`--dnc-space-${k}`, `${v}px`]),
);
push(
  'radii',
  Object.entries(tokens.radii).map(([k, v]) => [`--dnc-radius-${k}`, `${v}px`]),
);
push(
  'font sizes',
  Object.entries(tokens.typography.sizes).map(([k, v]) => [`--dnc-text-${k}`, `${v}px`]),
);
push(
  'line heights (unitless multipliers)',
  Object.entries(tokens.typography.lineHeights).map(([k, v]) => [`--dnc-leading-${k}`, v]),
);
push(
  'font weights',
  Object.entries(tokens.typography.weights).map(([k, v]) => [`--dnc-weight-${k}`, v]),
);

const banner = [
  '/*',
  ' * AUTO-GENERATED by scripts/generate-theme.mjs from @dnc/tokens.',
  ' * Do not edit by hand and do not add colours here: change packages/tokens',
  ' * and re-run `pnpm --filter @dnc/web-client gen:theme`.',
  ' */',
].join('\n');

const css = `${banner}\n\n:root {\n${lines.join('\n').trimEnd()}\n}\n`;
writeFileSync(resolve(here, '../app/theme.generated.css'), css);
console.log(`generated app/theme.generated.css (${css.split('\n').length} lines)`);
