// AUTO-GENERATED by scripts/generate-keys.mjs — do not edit by hand.
export type MessageKey =
  | 'a11y.clearFilter'
  | 'a11y.closeMenu'
  | 'a11y.openMenu'
  | 'a11y.switchLanguage'
  | 'a11y.toggleTheme'
  | 'area.all'
  | 'area.eventCount'
  | 'area.label'
  | 'auth.action.signIn'
  | 'auth.action.signOut'
  | 'auth.action.signUp'
  | 'auth.action.working'
  | 'auth.error.generic'
  | 'auth.error.offline'
  | 'auth.field.displayName'
  | 'auth.field.email'
  | 'auth.field.handle'
  | 'auth.field.identifier'
  | 'auth.field.password'
  | 'auth.hint.handle'
  | 'auth.hint.identifier'
  | 'auth.hint.password'
  | 'auth.page.signInBody'
  | 'auth.page.signInTitle'
  | 'auth.page.signUpBody'
  | 'auth.page.signUpTitle'
  | 'auth.prompt.body'
  | 'auth.prompt.title'
  | 'auth.switch.haveAccount'
  | 'auth.switch.noAccount'
  | 'blank.backHome'
  | 'blank.createEvent.body'
  | 'blank.createEvent.title'
  | 'blank.discover.body'
  | 'blank.discover.title'
  | 'blank.myEvents.body'
  | 'blank.myEvents.title'
  | 'blank.notFound.body'
  | 'blank.notFound.title'
  | 'blank.notifications.body'
  | 'blank.notifications.title'
  | 'common.appName'
  | 'common.comingSoon'
  | 'common.free'
  | 'common.language'
  | 'common.loading'
  | 'common.retry'
  | 'common.seeAll'
  | 'common.skipToContent'
  | 'datetime.timeZoneNote'
  | 'datetime.today'
  | 'datetime.tomorrow'
  | 'discover.areas.aria'
  | 'discover.areas.heading'
  | 'discover.category.language'
  | 'discover.category.outdoors'
  | 'discover.category.social'
  | 'discover.category.sports'
  | 'discover.category.wellness'
  | 'discover.empty.clear'
  | 'discover.empty.description'
  | 'discover.empty.title'
  | 'discover.filters.activeCount'
  | 'discover.filters.button'
  | 'discover.filters.category'
  | 'discover.filters.clear'
  | 'discover.filters.close'
  | 'discover.filters.done'
  | 'discover.filters.freeOnly'
  | 'discover.filters.title'
  | 'discover.map.aria'
  | 'discover.map.markerAria'
  | 'discover.map.placeholderNote'
  | 'discover.map.title'
  | 'discover.results.count'
  | 'discover.search.label'
  | 'discover.search.placeholder'
  | 'discover.title'
  | 'discover.view.label'
  | 'discover.view.list'
  | 'discover.view.map'
  | 'errors.auth.accountSuspended'
  | 'errors.auth.accountUnavailable'
  | 'errors.auth.emailTaken'
  | 'errors.auth.handleFormat'
  | 'errors.auth.handleTaken'
  | 'errors.auth.invalidCredentials'
  | 'errors.auth.invalidRefresh'
  | 'errors.auth.invalidToken'
  | 'errors.auth.trustLevelTooLow'
  | 'errors.auth.unauthenticated'
  | 'errors.chat.cannotMessageSelf'
  | 'errors.chat.conversationClosed'
  | 'errors.chat.conversationNotFound'
  | 'errors.chat.messageNotFound'
  | 'errors.chat.messagePayloadMismatch'
  | 'errors.chat.notRequestRecipient'
  | 'errors.chat.requestQuotaExhausted'
  | 'errors.chat.requestRefused'
  | 'errors.comment.cannotPinReply'
  | 'errors.comment.notAuthor'
  | 'errors.comment.notFound'
  | 'errors.comment.notThreadOwner'
  | 'errors.comment.parentNotFound'
  | 'errors.common.constraintViolated'
  | 'errors.common.duplicate'
  | 'errors.common.referenceNotFound'
  | 'errors.common.retryLater'
  | 'errors.event.notFound'
  | 'errors.event.notOrganizer'
  | 'errors.event.radiusRequiresCoordinates'
  | 'errors.event.underModeration'
  | 'errors.media.notFound'
  | 'errors.media.notUploaded'
  | 'errors.media.tooLarge'
  | 'errors.media.typeNotAllowed'
  | 'errors.post.notFound'
  | 'errors.post.notOwner'
  | 'errors.profile.notFound'
  | 'errors.profile.phoneInvalid'
  | 'errors.profile.phoneTaken'
  | 'event.card.almostFull'
  | 'event.card.attendees'
  | 'event.card.details'
  | 'event.card.hostedBy'
  | 'event.card.price'
  | 'event.card.startingSoon'
  | 'event.card.yours'
  | 'event.create.error'
  | 'event.create.field.area'
  | 'event.create.field.capacity'
  | 'event.create.field.description'
  | 'event.create.field.location'
  | 'event.create.field.startsAt'
  | 'event.create.field.title'
  | 'event.create.hint.capacity'
  | 'event.create.hint.description'
  | 'event.create.publish'
  | 'event.create.saveDraft'
  | 'event.create.title'
  | 'event.create.working'
  | 'event.detail.attendees'
  | 'event.detail.attendeesEmpty'
  | 'event.detail.attendeesSignedOut'
  | 'event.detail.full'
  | 'event.detail.hostedBy'
  | 'event.detail.joinWaitlistButton'
  | 'event.detail.missingBody'
  | 'event.detail.missingTitle'
  | 'event.detail.publish'
  | 'event.detail.rsvpButton'
  | 'event.detail.seatsLeft'
  | 'event.empty.cta'
  | 'event.empty.description'
  | 'event.empty.resetFilter'
  | 'event.empty.title'
  | 'event.requiredTrust'
  | 'event.status.cancelled'
  | 'event.status.draft'
  | 'event.status.pendingReview'
  | 'event.status.pending_review'
  | 'event.status.published'
  | 'event.status.suspended'
  | 'event.status.takenDown'
  | 'event.status.taken_down'
  | 'feed.activity.joinedMany'
  | 'feed.activity.joinedOne'
  | 'feed.activityJoined'
  | 'feed.card.comments'
  | 'feed.card.createdEvent'
  | 'feed.card.full'
  | 'feed.card.going'
  | 'feed.card.join'
  | 'feed.card.joined'
  | 'feed.card.menu'
  | 'feed.card.openEvent'
  | 'feed.card.seatsLeft'
  | 'feed.card.share'
  | 'feed.clearFilter'
  | 'feed.comments'
  | 'feed.composer.create'
  | 'feed.composer.placeholder'
  | 'feed.composerPlaceholder'
  | 'feed.createEvent'
  | 'feed.createdEvent'
  | 'feed.curatedEvent'
  | 'feed.empty.description'
  | 'feed.empty.reset'
  | 'feed.empty.title'
  | 'feed.emptyBody'
  | 'feed.emptyTitle'
  | 'feed.filter.all'
  | 'feed.filter.free'
  | 'feed.filter.label'
  | 'feed.filter.today'
  | 'feed.filter.weekend'
  | 'feed.filterAll'
  | 'feed.filterFree'
  | 'feed.filterToday'
  | 'feed.filterWeekend'
  | 'feed.going'
  | 'feed.joinWaitlist'
  | 'feed.loading'
  | 'feed.moreActions'
  | 'feed.onWaitlist'
  | 'feed.plusOthers'
  | 'feed.rsvp'
  | 'feed.seatsOf'
  | 'feed.share'
  | 'feed.title'
  | 'home.componentsHeading'
  | 'home.componentsNote'
  | 'home.eyebrow'
  | 'home.route.areas'
  | 'home.route.areasDescription'
  | 'home.route.detail'
  | 'home.route.detailDescription'
  | 'home.route.feed'
  | 'home.route.feedDescription'
  | 'home.route.profile'
  | 'home.route.profileDescription'
  | 'home.routesHeading'
  | 'home.routesNote'
  | 'home.status.planned'
  | 'home.status.ready'
  | 'home.subtitle'
  | 'home.title'
  | 'nav.createEvent'
  | 'nav.events'
  | 'nav.map'
  | 'nav.profile'
  | 'post.card.cityWide'
  | 'post.card.comments'
  | 'post.card.edited'
  | 'post.card.gallery'
  | 'post.card.posted'
  | 'post.card.react'
  | 'post.card.showMore'
  | 'post.composer.areaCityWide'
  | 'post.composer.areaLabel'
  | 'post.composer.back'
  | 'post.composer.bodyLabel'
  | 'post.composer.bodyPlaceholder'
  | 'post.composer.cancel'
  | 'post.composer.errorGeneric'
  | 'post.composer.errorOffline'
  | 'post.composer.kindLabel'
  | 'post.composer.open'
  | 'post.composer.remaining'
  | 'post.composer.skipMedia'
  | 'post.composer.submit'
  | 'post.composer.submitting'
  | 'post.composer.title'
  | 'post.composer.waitingUploads'
  | 'post.composer.you'
  | 'post.feed.empty'
  | 'post.feed.loading'
  | 'post.kind.lookingFor'
  | 'post.kind.notice'
  | 'post.kind.question'
  | 'post.kind.recommendation'
  | 'post.location.add'
  | 'post.location.labelField'
  | 'post.location.mapUnavailable'
  | 'post.location.pinned'
  | 'post.location.remove'
  | 'post.location.tapToPin'
  | 'post.media.addMore'
  | 'post.media.choose'
  | 'post.media.counter'
  | 'post.media.dropHint'
  | 'post.media.dropTitle'
  | 'post.media.next'
  | 'post.media.previewLabel'
  | 'post.media.previous'
  | 'post.media.rejectedSize'
  | 'post.media.rejectedType'
  | 'post.media.remove'
  | 'profile.action.cancel'
  | 'profile.action.edit'
  | 'profile.action.save'
  | 'profile.action.saving'
  | 'profile.error.save'
  | 'profile.field.bio'
  | 'profile.field.displayName'
  | 'profile.field.headline'
  | 'profile.field.homeArea'
  | 'profile.field.memberSince'
  | 'profile.field.noArea'
  | 'profile.field.phone'
  | 'profile.field.showArea'
  | 'profile.field.since'
  | 'profile.field.visibility'
  | 'profile.hint.headline'
  | 'profile.hint.phone'
  | 'profile.language.de'
  | 'profile.language.en'
  | 'profile.language.es'
  | 'profile.language.fr'
  | 'profile.language.ja'
  | 'profile.language.ko'
  | 'profile.language.other'
  | 'profile.language.ru'
  | 'profile.language.vi'
  | 'profile.language.zh'
  | 'profile.level.basic'
  | 'profile.level.conversational'
  | 'profile.level.fluent'
  | 'profile.level.native'
  | 'profile.missing.body'
  | 'profile.missing.title'
  | 'profile.section.about'
  | 'profile.stat.attended'
  | 'profile.stat.hosted'
  | 'profile.stat.rating'
  | 'profile.trust.next'
  | 'profile.visibility.members_only'
  | 'profile.visibility.private'
  | 'profile.visibility.public'
  | 'profile.visibilityHint.members_only'
  | 'profile.visibilityHint.private'
  | 'profile.visibilityHint.public'
  | 'rsvp.action.working'
  | 'rsvp.error.alreadyRsvped'
  | 'rsvp.error.generic'
  | 'rsvp.error.idempotencyKeyRequired'
  | 'rsvp.error.notRegistered'
  | 'rsvp.error.occurrenceClosed'
  | 'rsvp.error.occurrenceNotFound'
  | 'rsvp.error.suspended'
  | 'rsvp.error.trustTooLow'
  | 'shell.a11y.bottomNav'
  | 'shell.a11y.create'
  | 'shell.a11y.primaryNav'
  | 'shell.nav.create'
  | 'shell.nav.createEvent'
  | 'shell.nav.discover'
  | 'shell.nav.home'
  | 'shell.nav.myEvents'
  | 'shell.nav.notifications'
  | 'shell.nav.profile'
  | 'shell.rail.areas'
  | 'shell.rail.follow'
  | 'shell.rail.suggestions'
  | 'shell.rail.upcoming'
  | 'theme.dark'
  | 'theme.light'
  | 'theme.system'
  | 'trust.badge.aria'
  | 'trust.badge.short'
  | 'trust.level.t0'
  | 'trust.level.t1'
  | 'trust.level.t2'
  | 'trust.level.t3'
  | 'trust.level.t4'
  | 'trust.level.t5'
  | 'trust.requirement.accountAge7d'
  | 'trust.requirement.attend10Events'
  | 'trust.requirement.attend5Events'
  | 'trust.requirement.attendFirstEvent'
  | 'trust.requirement.host5Events'
  | 'trust.requirement.hostFirstEvent'
  | 'trust.requirement.resolveReports'
  | 'trust.requirement.verifyContact';

export const MESSAGE_KEYS = [
  'a11y.clearFilter',
  'a11y.closeMenu',
  'a11y.openMenu',
  'a11y.switchLanguage',
  'a11y.toggleTheme',
  'area.all',
  'area.eventCount',
  'area.label',
  'auth.action.signIn',
  'auth.action.signOut',
  'auth.action.signUp',
  'auth.action.working',
  'auth.error.generic',
  'auth.error.offline',
  'auth.field.displayName',
  'auth.field.email',
  'auth.field.handle',
  'auth.field.identifier',
  'auth.field.password',
  'auth.hint.handle',
  'auth.hint.identifier',
  'auth.hint.password',
  'auth.page.signInBody',
  'auth.page.signInTitle',
  'auth.page.signUpBody',
  'auth.page.signUpTitle',
  'auth.prompt.body',
  'auth.prompt.title',
  'auth.switch.haveAccount',
  'auth.switch.noAccount',
  'blank.backHome',
  'blank.createEvent.body',
  'blank.createEvent.title',
  'blank.discover.body',
  'blank.discover.title',
  'blank.myEvents.body',
  'blank.myEvents.title',
  'blank.notFound.body',
  'blank.notFound.title',
  'blank.notifications.body',
  'blank.notifications.title',
  'common.appName',
  'common.comingSoon',
  'common.free',
  'common.language',
  'common.loading',
  'common.retry',
  'common.seeAll',
  'common.skipToContent',
  'datetime.timeZoneNote',
  'datetime.today',
  'datetime.tomorrow',
  'discover.areas.aria',
  'discover.areas.heading',
  'discover.category.language',
  'discover.category.outdoors',
  'discover.category.social',
  'discover.category.sports',
  'discover.category.wellness',
  'discover.empty.clear',
  'discover.empty.description',
  'discover.empty.title',
  'discover.filters.activeCount',
  'discover.filters.button',
  'discover.filters.category',
  'discover.filters.clear',
  'discover.filters.close',
  'discover.filters.done',
  'discover.filters.freeOnly',
  'discover.filters.title',
  'discover.map.aria',
  'discover.map.markerAria',
  'discover.map.placeholderNote',
  'discover.map.title',
  'discover.results.count',
  'discover.search.label',
  'discover.search.placeholder',
  'discover.title',
  'discover.view.label',
  'discover.view.list',
  'discover.view.map',
  'errors.auth.accountSuspended',
  'errors.auth.accountUnavailable',
  'errors.auth.emailTaken',
  'errors.auth.handleFormat',
  'errors.auth.handleTaken',
  'errors.auth.invalidCredentials',
  'errors.auth.invalidRefresh',
  'errors.auth.invalidToken',
  'errors.auth.trustLevelTooLow',
  'errors.auth.unauthenticated',
  'errors.chat.cannotMessageSelf',
  'errors.chat.conversationClosed',
  'errors.chat.conversationNotFound',
  'errors.chat.messageNotFound',
  'errors.chat.messagePayloadMismatch',
  'errors.chat.notRequestRecipient',
  'errors.chat.requestQuotaExhausted',
  'errors.chat.requestRefused',
  'errors.comment.cannotPinReply',
  'errors.comment.notAuthor',
  'errors.comment.notFound',
  'errors.comment.notThreadOwner',
  'errors.comment.parentNotFound',
  'errors.common.constraintViolated',
  'errors.common.duplicate',
  'errors.common.referenceNotFound',
  'errors.common.retryLater',
  'errors.event.notFound',
  'errors.event.notOrganizer',
  'errors.event.radiusRequiresCoordinates',
  'errors.event.underModeration',
  'errors.media.notFound',
  'errors.media.notUploaded',
  'errors.media.tooLarge',
  'errors.media.typeNotAllowed',
  'errors.post.notFound',
  'errors.post.notOwner',
  'errors.profile.notFound',
  'errors.profile.phoneInvalid',
  'errors.profile.phoneTaken',
  'event.card.almostFull',
  'event.card.attendees',
  'event.card.details',
  'event.card.hostedBy',
  'event.card.price',
  'event.card.startingSoon',
  'event.card.yours',
  'event.create.error',
  'event.create.field.area',
  'event.create.field.capacity',
  'event.create.field.description',
  'event.create.field.location',
  'event.create.field.startsAt',
  'event.create.field.title',
  'event.create.hint.capacity',
  'event.create.hint.description',
  'event.create.publish',
  'event.create.saveDraft',
  'event.create.title',
  'event.create.working',
  'event.detail.attendees',
  'event.detail.attendeesEmpty',
  'event.detail.attendeesSignedOut',
  'event.detail.full',
  'event.detail.hostedBy',
  'event.detail.joinWaitlistButton',
  'event.detail.missingBody',
  'event.detail.missingTitle',
  'event.detail.publish',
  'event.detail.rsvpButton',
  'event.detail.seatsLeft',
  'event.empty.cta',
  'event.empty.description',
  'event.empty.resetFilter',
  'event.empty.title',
  'event.requiredTrust',
  'event.status.cancelled',
  'event.status.draft',
  'event.status.pendingReview',
  'event.status.pending_review',
  'event.status.published',
  'event.status.suspended',
  'event.status.takenDown',
  'event.status.taken_down',
  'feed.activity.joinedMany',
  'feed.activity.joinedOne',
  'feed.activityJoined',
  'feed.card.comments',
  'feed.card.createdEvent',
  'feed.card.full',
  'feed.card.going',
  'feed.card.join',
  'feed.card.joined',
  'feed.card.menu',
  'feed.card.openEvent',
  'feed.card.seatsLeft',
  'feed.card.share',
  'feed.clearFilter',
  'feed.comments',
  'feed.composer.create',
  'feed.composer.placeholder',
  'feed.composerPlaceholder',
  'feed.createEvent',
  'feed.createdEvent',
  'feed.curatedEvent',
  'feed.empty.description',
  'feed.empty.reset',
  'feed.empty.title',
  'feed.emptyBody',
  'feed.emptyTitle',
  'feed.filter.all',
  'feed.filter.free',
  'feed.filter.label',
  'feed.filter.today',
  'feed.filter.weekend',
  'feed.filterAll',
  'feed.filterFree',
  'feed.filterToday',
  'feed.filterWeekend',
  'feed.going',
  'feed.joinWaitlist',
  'feed.loading',
  'feed.moreActions',
  'feed.onWaitlist',
  'feed.plusOthers',
  'feed.rsvp',
  'feed.seatsOf',
  'feed.share',
  'feed.title',
  'home.componentsHeading',
  'home.componentsNote',
  'home.eyebrow',
  'home.route.areas',
  'home.route.areasDescription',
  'home.route.detail',
  'home.route.detailDescription',
  'home.route.feed',
  'home.route.feedDescription',
  'home.route.profile',
  'home.route.profileDescription',
  'home.routesHeading',
  'home.routesNote',
  'home.status.planned',
  'home.status.ready',
  'home.subtitle',
  'home.title',
  'nav.createEvent',
  'nav.events',
  'nav.map',
  'nav.profile',
  'post.card.cityWide',
  'post.card.comments',
  'post.card.edited',
  'post.card.gallery',
  'post.card.posted',
  'post.card.react',
  'post.card.showMore',
  'post.composer.areaCityWide',
  'post.composer.areaLabel',
  'post.composer.back',
  'post.composer.bodyLabel',
  'post.composer.bodyPlaceholder',
  'post.composer.cancel',
  'post.composer.errorGeneric',
  'post.composer.errorOffline',
  'post.composer.kindLabel',
  'post.composer.open',
  'post.composer.remaining',
  'post.composer.skipMedia',
  'post.composer.submit',
  'post.composer.submitting',
  'post.composer.title',
  'post.composer.waitingUploads',
  'post.composer.you',
  'post.feed.empty',
  'post.feed.loading',
  'post.kind.lookingFor',
  'post.kind.notice',
  'post.kind.question',
  'post.kind.recommendation',
  'post.location.add',
  'post.location.labelField',
  'post.location.mapUnavailable',
  'post.location.pinned',
  'post.location.remove',
  'post.location.tapToPin',
  'post.media.addMore',
  'post.media.choose',
  'post.media.counter',
  'post.media.dropHint',
  'post.media.dropTitle',
  'post.media.next',
  'post.media.previewLabel',
  'post.media.previous',
  'post.media.rejectedSize',
  'post.media.rejectedType',
  'post.media.remove',
  'profile.action.cancel',
  'profile.action.edit',
  'profile.action.save',
  'profile.action.saving',
  'profile.error.save',
  'profile.field.bio',
  'profile.field.displayName',
  'profile.field.headline',
  'profile.field.homeArea',
  'profile.field.memberSince',
  'profile.field.noArea',
  'profile.field.phone',
  'profile.field.showArea',
  'profile.field.since',
  'profile.field.visibility',
  'profile.hint.headline',
  'profile.hint.phone',
  'profile.language.de',
  'profile.language.en',
  'profile.language.es',
  'profile.language.fr',
  'profile.language.ja',
  'profile.language.ko',
  'profile.language.other',
  'profile.language.ru',
  'profile.language.vi',
  'profile.language.zh',
  'profile.level.basic',
  'profile.level.conversational',
  'profile.level.fluent',
  'profile.level.native',
  'profile.missing.body',
  'profile.missing.title',
  'profile.section.about',
  'profile.stat.attended',
  'profile.stat.hosted',
  'profile.stat.rating',
  'profile.trust.next',
  'profile.visibility.members_only',
  'profile.visibility.private',
  'profile.visibility.public',
  'profile.visibilityHint.members_only',
  'profile.visibilityHint.private',
  'profile.visibilityHint.public',
  'rsvp.action.working',
  'rsvp.error.alreadyRsvped',
  'rsvp.error.generic',
  'rsvp.error.idempotencyKeyRequired',
  'rsvp.error.notRegistered',
  'rsvp.error.occurrenceClosed',
  'rsvp.error.occurrenceNotFound',
  'rsvp.error.suspended',
  'rsvp.error.trustTooLow',
  'shell.a11y.bottomNav',
  'shell.a11y.create',
  'shell.a11y.primaryNav',
  'shell.nav.create',
  'shell.nav.createEvent',
  'shell.nav.discover',
  'shell.nav.home',
  'shell.nav.myEvents',
  'shell.nav.notifications',
  'shell.nav.profile',
  'shell.rail.areas',
  'shell.rail.follow',
  'shell.rail.suggestions',
  'shell.rail.upcoming',
  'theme.dark',
  'theme.light',
  'theme.system',
  'trust.badge.aria',
  'trust.badge.short',
  'trust.level.t0',
  'trust.level.t1',
  'trust.level.t2',
  'trust.level.t3',
  'trust.level.t4',
  'trust.level.t5',
  'trust.requirement.accountAge7d',
  'trust.requirement.attend10Events',
  'trust.requirement.attend5Events',
  'trust.requirement.attendFirstEvent',
  'trust.requirement.host5Events',
  'trust.requirement.hostFirstEvent',
  'trust.requirement.resolveReports',
  'trust.requirement.verifyContact',
] as const;
