// AUTO-GENERATED by scripts/generate-keys.mjs — do not edit by hand.
export type MessageKey =
  | 'a11y.clearFilter'
  | 'a11y.closeMenu'
  | 'a11y.openMenu'
  | 'a11y.switchLanguage'
  | 'a11y.toggleTheme'
  | 'area.all'
  | 'area.eventCount'
  | 'area.label'
  | 'common.appName'
  | 'common.comingSoon'
  | 'common.free'
  | 'common.language'
  | 'common.loading'
  | 'common.retry'
  | 'common.seeAll'
  | 'common.skipToContent'
  | 'datetime.timeZoneNote'
  | 'datetime.today'
  | 'datetime.tomorrow'
  | 'event.card.almostFull'
  | 'event.card.attendees'
  | 'event.card.hostedBy'
  | 'event.card.price'
  | 'event.card.startingSoon'
  | 'event.detail.full'
  | 'event.detail.joinWaitlistButton'
  | 'event.detail.rsvpButton'
  | 'event.detail.seatsLeft'
  | 'event.empty.cta'
  | 'event.empty.description'
  | 'event.empty.resetFilter'
  | 'event.empty.title'
  | 'event.requiredTrust'
  | 'event.status.cancelled'
  | 'event.status.draft'
  | 'event.status.pendingReview'
  | 'event.status.published'
  | 'event.status.suspended'
  | 'event.status.takenDown'
  | 'home.componentsHeading'
  | 'home.componentsNote'
  | 'home.eyebrow'
  | 'home.route.areas'
  | 'home.route.areasDescription'
  | 'home.route.detail'
  | 'home.route.detailDescription'
  | 'home.route.feed'
  | 'home.route.feedDescription'
  | 'home.route.profile'
  | 'home.route.profileDescription'
  | 'home.routesHeading'
  | 'home.routesNote'
  | 'home.status.planned'
  | 'home.status.ready'
  | 'home.subtitle'
  | 'home.title'
  | 'nav.createEvent'
  | 'nav.events'
  | 'nav.map'
  | 'nav.profile'
  | 'rsvp.error.alreadyRsvped'
  | 'rsvp.error.occurrenceClosed'
  | 'rsvp.error.suspended'
  | 'rsvp.error.trustTooLow'
  | 'theme.dark'
  | 'theme.light'
  | 'theme.system'
  | 'trust.badge.aria'
  | 'trust.badge.short'
  | 'trust.level.t0'
  | 'trust.level.t1'
  | 'trust.level.t2'
  | 'trust.level.t3'
  | 'trust.level.t4'
  | 'trust.level.t5'
  | 'trust.requirement.accountAge7d'
  | 'trust.requirement.attend10Events'
  | 'trust.requirement.attend5Events'
  | 'trust.requirement.attendFirstEvent'
  | 'trust.requirement.host5Events'
  | 'trust.requirement.hostFirstEvent'
  | 'trust.requirement.resolveReports'
  | 'trust.requirement.verifyContact';

export const MESSAGE_KEYS = [
  'a11y.clearFilter',
  'a11y.closeMenu',
  'a11y.openMenu',
  'a11y.switchLanguage',
  'a11y.toggleTheme',
  'area.all',
  'area.eventCount',
  'area.label',
  'common.appName',
  'common.comingSoon',
  'common.free',
  'common.language',
  'common.loading',
  'common.retry',
  'common.seeAll',
  'common.skipToContent',
  'datetime.timeZoneNote',
  'datetime.today',
  'datetime.tomorrow',
  'event.card.almostFull',
  'event.card.attendees',
  'event.card.hostedBy',
  'event.card.price',
  'event.card.startingSoon',
  'event.detail.full',
  'event.detail.joinWaitlistButton',
  'event.detail.rsvpButton',
  'event.detail.seatsLeft',
  'event.empty.cta',
  'event.empty.description',
  'event.empty.resetFilter',
  'event.empty.title',
  'event.requiredTrust',
  'event.status.cancelled',
  'event.status.draft',
  'event.status.pendingReview',
  'event.status.published',
  'event.status.suspended',
  'event.status.takenDown',
  'home.componentsHeading',
  'home.componentsNote',
  'home.eyebrow',
  'home.route.areas',
  'home.route.areasDescription',
  'home.route.detail',
  'home.route.detailDescription',
  'home.route.feed',
  'home.route.feedDescription',
  'home.route.profile',
  'home.route.profileDescription',
  'home.routesHeading',
  'home.routesNote',
  'home.status.planned',
  'home.status.ready',
  'home.subtitle',
  'home.title',
  'nav.createEvent',
  'nav.events',
  'nav.map',
  'nav.profile',
  'rsvp.error.alreadyRsvped',
  'rsvp.error.occurrenceClosed',
  'rsvp.error.suspended',
  'rsvp.error.trustTooLow',
  'theme.dark',
  'theme.light',
  'theme.system',
  'trust.badge.aria',
  'trust.badge.short',
  'trust.level.t0',
  'trust.level.t1',
  'trust.level.t2',
  'trust.level.t3',
  'trust.level.t4',
  'trust.level.t5',
  'trust.requirement.accountAge7d',
  'trust.requirement.attend10Events',
  'trust.requirement.attend5Events',
  'trust.requirement.attendFirstEvent',
  'trust.requirement.host5Events',
  'trust.requirement.hostFirstEvent',
  'trust.requirement.resolveReports',
  'trust.requirement.verifyContact',
] as const;
