// AUTO-GENERATED by scripts/generate-keys.mjs — do not edit by hand.
export type MessageKey =
  | 'a11y.clearFilter'
  | 'a11y.closeMenu'
  | 'a11y.openMenu'
  | 'a11y.switchLanguage'
  | 'a11y.toggleTheme'
  | 'admin.audit.action.content_hidden'
  | 'admin.audit.action.content_restored'
  | 'admin.audit.action.event_restored'
  | 'admin.audit.action.event_suspended'
  | 'admin.audit.action.event_taken_down'
  | 'admin.audit.action.report_dismissed'
  | 'admin.audit.action.severity_changed'
  | 'admin.audit.action.user_suspended'
  | 'admin.audit.action.user_unsuspended'
  | 'admin.audit.column.action'
  | 'admin.audit.column.actor'
  | 'admin.audit.column.change'
  | 'admin.audit.column.entity'
  | 'admin.audit.column.reason'
  | 'admin.audit.column.time'
  | 'admin.audit.empty'
  | 'admin.audit.entityType.comment'
  | 'admin.audit.entityType.event'
  | 'admin.audit.entityType.moderation_ticket'
  | 'admin.audit.entityType.post'
  | 'admin.audit.entityType.user'
  | 'admin.audit.error.title'
  | 'admin.audit.filter.action'
  | 'admin.audit.filter.actor'
  | 'admin.audit.filter.any'
  | 'admin.audit.filter.apply'
  | 'admin.audit.filter.entityType'
  | 'admin.audit.filter.from'
  | 'admin.audit.filter.reset'
  | 'admin.audit.filter.to'
  | 'admin.audit.loadMore'
  | 'admin.audit.readOnly'
  | 'admin.audit.severity.critical'
  | 'admin.audit.severity.info'
  | 'admin.audit.severity.notice'
  | 'admin.audit.severity.warning'
  | 'admin.audit.system'
  | 'admin.audit.title'
  | 'admin.header.signedInAs'
  | 'admin.health.checkedAt'
  | 'admin.health.dependency.database'
  | 'admin.health.dependency.redisCache'
  | 'admin.health.dependency.redisQueue'
  | 'admin.health.dependencyStatus.down'
  | 'admin.health.dependencyStatus.up'
  | 'admin.health.environmentLabel'
  | 'admin.health.state.allUp.body'
  | 'admin.health.state.allUp.title'
  | 'admin.health.state.degraded.body'
  | 'admin.health.state.degraded.title'
  | 'admin.health.state.unreachable.body'
  | 'admin.health.state.unreachable.title'
  | 'admin.health.title'
  | 'admin.health.uptimeLabel'
  | 'admin.login.body'
  | 'admin.login.rejected'
  | 'admin.login.title'
  | 'admin.moderation.action.changeSeverity'
  | 'admin.moderation.action.dismiss'
  | 'admin.moderation.action.hide_content'
  | 'admin.moderation.action.restore_content'
  | 'admin.moderation.action.restore_event'
  | 'admin.moderation.action.suspend_event'
  | 'admin.moderation.action.suspend_user'
  | 'admin.moderation.action.take_down_event'
  | 'admin.moderation.action.unsuspend_user'
  | 'admin.moderation.actionType.content_hidden'
  | 'admin.moderation.actionType.content_restored'
  | 'admin.moderation.actionType.event_restored'
  | 'admin.moderation.actionType.event_suspended'
  | 'admin.moderation.actionType.event_taken_down'
  | 'admin.moderation.actionType.no_action'
  | 'admin.moderation.actionType.severity_changed'
  | 'admin.moderation.actionType.user_suspended'
  | 'admin.moderation.actionType.user_unsuspended'
  | 'admin.moderation.form.cancel'
  | 'admin.moderation.form.duration'
  | 'admin.moderation.form.durationHint'
  | 'admin.moderation.form.errorGeneric'
  | 'admin.moderation.form.note'
  | 'admin.moderation.form.noteCounter'
  | 'admin.moderation.form.reason'
  | 'admin.moderation.form.severity'
  | 'admin.moderation.form.submit'
  | 'admin.moderation.form.submitting'
  | 'admin.moderation.queue.column.closedAt'
  | 'admin.moderation.queue.column.firstReported'
  | 'admin.moderation.queue.column.outcome'
  | 'admin.moderation.queue.column.reasons'
  | 'admin.moderation.queue.column.reports'
  | 'admin.moderation.queue.column.severity'
  | 'admin.moderation.queue.column.sla'
  | 'admin.moderation.queue.column.target'
  | 'admin.moderation.queue.empty.closed'
  | 'admin.moderation.queue.empty.open'
  | 'admin.moderation.queue.error.body'
  | 'admin.moderation.queue.error.title'
  | 'admin.moderation.queue.filter.allSeverities'
  | 'admin.moderation.queue.filter.closed'
  | 'admin.moderation.queue.filter.open'
  | 'admin.moderation.queue.loadMore'
  | 'admin.moderation.queue.title'
  | 'admin.moderation.severity.critical'
  | 'admin.moderation.severity.high'
  | 'admin.moderation.severity.low'
  | 'admin.moderation.severity.normal'
  | 'admin.moderation.sla.dueSoon'
  | 'admin.moderation.sla.normal'
  | 'admin.moderation.sla.overdue'
  | 'admin.moderation.sla.stopped'
  | 'admin.moderation.targetType.comment'
  | 'admin.moderation.targetType.event'
  | 'admin.moderation.targetType.post'
  | 'admin.moderation.targetType.user'
  | 'admin.moderation.ticket.actorSystem'
  | 'admin.moderation.ticket.addAction'
  | 'admin.moderation.ticket.back'
  | 'admin.moderation.ticket.currentStatus'
  | 'admin.moderation.ticket.error.title'
  | 'admin.moderation.ticket.historyEmpty'
  | 'admin.moderation.ticket.historyTitle'
  | 'admin.moderation.ticket.noDescription'
  | 'admin.moderation.ticket.owner'
  | 'admin.moderation.ticket.reporter'
  | 'admin.moderation.ticket.reporterDeleted'
  | 'admin.moderation.ticket.reportsTitle'
  | 'admin.moderation.ticket.snapshotTitle'
  | 'admin.moderation.ticket.suspendedUntil'
  | 'admin.moderation.ticket.targetDeleted'
  | 'admin.moderation.ticketStatus.dismissed'
  | 'admin.moderation.ticketStatus.open'
  | 'admin.moderation.ticketStatus.resolved'
  | 'admin.nav.auditLog'
  | 'admin.nav.moderationQueue'
  | 'admin.nav.overview'
  | 'admin.nav.systemHealth'
  | 'admin.overview.body'
  | 'admin.overview.title'
  | 'area.all'
  | 'area.eventCount'
  | 'area.label'
  | 'auth.action.signIn'
  | 'auth.action.signOut'
  | 'auth.action.signUp'
  | 'auth.action.working'
  | 'auth.error.generic'
  | 'auth.error.offline'
  | 'auth.field.displayName'
  | 'auth.field.email'
  | 'auth.field.handle'
  | 'auth.field.identifier'
  | 'auth.field.password'
  | 'auth.hint.handle'
  | 'auth.hint.identifier'
  | 'auth.hint.password'
  | 'auth.page.signInBody'
  | 'auth.page.signInTitle'
  | 'auth.page.signUpBody'
  | 'auth.page.signUpTitle'
  | 'auth.prompt.body'
  | 'auth.prompt.title'
  | 'auth.switch.haveAccount'
  | 'auth.switch.noAccount'
  | 'blank.backHome'
  | 'blank.createEvent.body'
  | 'blank.createEvent.title'
  | 'blank.discover.body'
  | 'blank.discover.title'
  | 'blank.myEvents.body'
  | 'blank.myEvents.title'
  | 'blank.notFound.body'
  | 'blank.notFound.title'
  | 'blank.notifications.body'
  | 'blank.notifications.title'
  | 'common.appName'
  | 'common.comingSoon'
  | 'common.free'
  | 'common.language'
  | 'common.loading'
  | 'common.retry'
  | 'common.seeAll'
  | 'common.skipToContent'
  | 'datetime.timeZoneNote'
  | 'datetime.today'
  | 'datetime.tomorrow'
  | 'discover.areas.aria'
  | 'discover.areas.heading'
  | 'discover.category.language'
  | 'discover.category.outdoors'
  | 'discover.category.social'
  | 'discover.category.sports'
  | 'discover.category.wellness'
  | 'discover.empty.clear'
  | 'discover.empty.description'
  | 'discover.empty.title'
  | 'discover.filters.activeCount'
  | 'discover.filters.button'
  | 'discover.filters.category'
  | 'discover.filters.clear'
  | 'discover.filters.close'
  | 'discover.filters.done'
  | 'discover.filters.freeOnly'
  | 'discover.filters.title'
  | 'discover.map.aria'
  | 'discover.map.markerAria'
  | 'discover.map.placeholderNote'
  | 'discover.map.title'
  | 'discover.results.count'
  | 'discover.search.label'
  | 'discover.search.placeholder'
  | 'discover.title'
  | 'discover.view.label'
  | 'discover.view.list'
  | 'discover.view.map'
  | 'errors.area.notFound'
  | 'errors.area.outsideCoverage'
  | 'errors.auth.accountSuspended'
  | 'errors.auth.accountUnavailable'
  | 'errors.auth.emailTaken'
  | 'errors.auth.handleFormat'
  | 'errors.auth.handleTaken'
  | 'errors.auth.invalidCredentials'
  | 'errors.auth.invalidRefresh'
  | 'errors.auth.invalidToken'
  | 'errors.auth.roleNotAllowed'
  | 'errors.auth.trustLevelTooLow'
  | 'errors.auth.unauthenticated'
  | 'errors.block.selfNotAllowed'
  | 'errors.chat.cannotMessageSelf'
  | 'errors.chat.conversationClosed'
  | 'errors.chat.conversationNotFound'
  | 'errors.chat.messageNotFound'
  | 'errors.chat.messagePayloadMismatch'
  | 'errors.chat.notRequestRecipient'
  | 'errors.chat.requestQuotaExhausted'
  | 'errors.chat.requestRefused'
  | 'errors.comment.cannotPinReply'
  | 'errors.comment.notAuthor'
  | 'errors.comment.notFound'
  | 'errors.comment.notThreadOwner'
  | 'errors.comment.parentNotFound'
  | 'errors.common.constraintViolated'
  | 'errors.common.duplicate'
  | 'errors.common.idempotencyKeyRequired'
  | 'errors.common.referenceNotFound'
  | 'errors.common.retryLater'
  | 'errors.content.underModeration'
  | 'errors.event.notFound'
  | 'errors.event.notOrganizer'
  | 'errors.event.radiusRequiresCoordinates'
  | 'errors.event.underModeration'
  | 'errors.media.notFound'
  | 'errors.media.notUploaded'
  | 'errors.media.tooLarge'
  | 'errors.media.typeNotAllowed'
  | 'errors.moderation.conflictOfInterest'
  | 'errors.moderation.invalidState'
  | 'errors.moderation.noteTooLong'
  | 'errors.moderation.noteTooShort'
  | 'errors.moderation.reasonRequired'
  | 'errors.moderation.selfNotAllowed'
  | 'errors.moderation.suspensionTooLong'
  | 'errors.moderation.targetNotFound'
  | 'errors.moderation.targetNotInTicket'
  | 'errors.moderation.targetProtected'
  | 'errors.moderation.ticketAlreadyClosed'
  | 'errors.moderation.ticketNotFound'
  | 'errors.post.notFound'
  | 'errors.post.notOwner'
  | 'errors.profile.notFound'
  | 'errors.profile.phoneInvalid'
  | 'errors.profile.phoneTaken'
  | 'errors.report.descriptionTooLong'
  | 'errors.report.rateLimited'
  | 'errors.report.selfNotAllowed'
  | 'errors.report.targetNotFound'
  | 'event.card.almostFull'
  | 'event.card.attendees'
  | 'event.card.details'
  | 'event.card.hostedBy'
  | 'event.card.price'
  | 'event.card.startingSoon'
  | 'event.card.yours'
  | 'event.create.error'
  | 'event.create.field.area'
  | 'event.create.field.capacity'
  | 'event.create.field.description'
  | 'event.create.field.location'
  | 'event.create.field.startsAt'
  | 'event.create.field.title'
  | 'event.create.hint.capacity'
  | 'event.create.hint.description'
  | 'event.create.publish'
  | 'event.create.saveDraft'
  | 'event.create.title'
  | 'event.create.working'
  | 'event.detail.attendees'
  | 'event.detail.attendeesEmpty'
  | 'event.detail.attendeesSignedOut'
  | 'event.detail.full'
  | 'event.detail.hostedBy'
  | 'event.detail.joinWaitlistButton'
  | 'event.detail.missingBody'
  | 'event.detail.missingTitle'
  | 'event.detail.publish'
  | 'event.detail.rsvpButton'
  | 'event.detail.seatsLeft'
  | 'event.empty.cta'
  | 'event.empty.description'
  | 'event.empty.resetFilter'
  | 'event.empty.title'
  | 'event.requiredTrust'
  | 'event.status.cancelled'
  | 'event.status.draft'
  | 'event.status.pendingReview'
  | 'event.status.pending_review'
  | 'event.status.published'
  | 'event.status.suspended'
  | 'event.status.takenDown'
  | 'event.status.taken_down'
  | 'feed.activity.joinedMany'
  | 'feed.activity.joinedOne'
  | 'feed.activityJoined'
  | 'feed.card.comments'
  | 'feed.card.createdEvent'
  | 'feed.card.full'
  | 'feed.card.going'
  | 'feed.card.join'
  | 'feed.card.joined'
  | 'feed.card.menu'
  | 'feed.card.openEvent'
  | 'feed.card.seatsLeft'
  | 'feed.card.share'
  | 'feed.clearFilter'
  | 'feed.comments'
  | 'feed.composer.create'
  | 'feed.composer.placeholder'
  | 'feed.composerPlaceholder'
  | 'feed.createEvent'
  | 'feed.createdEvent'
  | 'feed.curatedEvent'
  | 'feed.empty.description'
  | 'feed.empty.reset'
  | 'feed.empty.title'
  | 'feed.emptyBody'
  | 'feed.emptyTitle'
  | 'feed.filter.all'
  | 'feed.filter.free'
  | 'feed.filter.label'
  | 'feed.filter.today'
  | 'feed.filter.weekend'
  | 'feed.filterAll'
  | 'feed.filterFree'
  | 'feed.filterToday'
  | 'feed.filterWeekend'
  | 'feed.going'
  | 'feed.joinWaitlist'
  | 'feed.loading'
  | 'feed.moreActions'
  | 'feed.onWaitlist'
  | 'feed.plusOthers'
  | 'feed.rsvp'
  | 'feed.seatsOf'
  | 'feed.share'
  | 'feed.title'
  | 'home.componentsHeading'
  | 'home.componentsNote'
  | 'home.eyebrow'
  | 'home.route.areas'
  | 'home.route.areasDescription'
  | 'home.route.detail'
  | 'home.route.detailDescription'
  | 'home.route.feed'
  | 'home.route.feedDescription'
  | 'home.route.profile'
  | 'home.route.profileDescription'
  | 'home.routesHeading'
  | 'home.routesNote'
  | 'home.status.planned'
  | 'home.status.ready'
  | 'home.subtitle'
  | 'home.title'
  | 'nav.createEvent'
  | 'nav.events'
  | 'nav.map'
  | 'nav.profile'
  | 'post.card.cityWide'
  | 'post.card.comments'
  | 'post.card.edited'
  | 'post.card.gallery'
  | 'post.card.posted'
  | 'post.card.react'
  | 'post.card.showMore'
  | 'post.composer.areaCityWide'
  | 'post.composer.areaLabel'
  | 'post.composer.back'
  | 'post.composer.bodyLabel'
  | 'post.composer.bodyPlaceholder'
  | 'post.composer.cancel'
  | 'post.composer.errorGeneric'
  | 'post.composer.errorOffline'
  | 'post.composer.kindLabel'
  | 'post.composer.open'
  | 'post.composer.remaining'
  | 'post.composer.skipMedia'
  | 'post.composer.submit'
  | 'post.composer.submitting'
  | 'post.composer.title'
  | 'post.composer.waitingUploads'
  | 'post.composer.you'
  | 'post.feed.empty'
  | 'post.feed.loading'
  | 'post.kind.lookingFor'
  | 'post.kind.notice'
  | 'post.kind.question'
  | 'post.kind.recommendation'
  | 'post.location.add'
  | 'post.location.labelField'
  | 'post.location.mapUnavailable'
  | 'post.location.pinned'
  | 'post.location.remove'
  | 'post.location.tapToPin'
  | 'post.media.addMore'
  | 'post.media.choose'
  | 'post.media.counter'
  | 'post.media.dropHint'
  | 'post.media.dropTitle'
  | 'post.media.next'
  | 'post.media.previewLabel'
  | 'post.media.previous'
  | 'post.media.rejectedSize'
  | 'post.media.rejectedType'
  | 'post.media.remove'
  | 'profile.action.cancel'
  | 'profile.action.edit'
  | 'profile.action.save'
  | 'profile.action.saving'
  | 'profile.error.save'
  | 'profile.field.bio'
  | 'profile.field.displayName'
  | 'profile.field.headline'
  | 'profile.field.homeArea'
  | 'profile.field.memberSince'
  | 'profile.field.noArea'
  | 'profile.field.phone'
  | 'profile.field.showArea'
  | 'profile.field.since'
  | 'profile.field.visibility'
  | 'profile.hint.headline'
  | 'profile.hint.phone'
  | 'profile.language.de'
  | 'profile.language.en'
  | 'profile.language.es'
  | 'profile.language.fr'
  | 'profile.language.ja'
  | 'profile.language.ko'
  | 'profile.language.other'
  | 'profile.language.ru'
  | 'profile.language.vi'
  | 'profile.language.zh'
  | 'profile.level.basic'
  | 'profile.level.conversational'
  | 'profile.level.fluent'
  | 'profile.level.native'
  | 'profile.missing.body'
  | 'profile.missing.title'
  | 'profile.section.about'
  | 'profile.stat.attended'
  | 'profile.stat.hosted'
  | 'profile.stat.rating'
  | 'profile.trust.next'
  | 'profile.visibility.members_only'
  | 'profile.visibility.private'
  | 'profile.visibility.public'
  | 'profile.visibilityHint.members_only'
  | 'profile.visibilityHint.private'
  | 'profile.visibilityHint.public'
  | 'role.admin.label'
  | 'role.curator.label'
  | 'role.moderator.label'
  | 'role.superAdmin.label'
  | 'rsvp.action.working'
  | 'rsvp.error.alreadyRsvped'
  | 'rsvp.error.generic'
  | 'rsvp.error.idempotencyKeyRequired'
  | 'rsvp.error.notRegistered'
  | 'rsvp.error.occurrenceClosed'
  | 'rsvp.error.occurrenceNotFound'
  | 'rsvp.error.suspended'
  | 'rsvp.error.trustTooLow'
  | 'safety.block.action'
  | 'safety.block.actionAuthor'
  | 'safety.block.actionOrganizer'
  | 'safety.block.blocked'
  | 'safety.block.cancel'
  | 'safety.block.confirm'
  | 'safety.block.confirmBody'
  | 'safety.block.confirmTitle'
  | 'safety.block.error'
  | 'safety.block.list.blockedAt'
  | 'safety.block.list.empty'
  | 'safety.block.list.title'
  | 'safety.block.unblock'
  | 'safety.block.working'
  | 'safety.label.contentHidden'
  | 'safety.label.eventSuspended'
  | 'safety.label.eventTakenDown'
  | 'safety.label.eventUnavailable'
  | 'safety.menu.more'
  | 'safety.report.action'
  | 'safety.report.alsoBlock'
  | 'safety.report.close'
  | 'safety.report.descriptionCounter'
  | 'safety.report.descriptionLabel'
  | 'safety.report.emergency_first'
  | 'safety.report.errorGeneric'
  | 'safety.report.errorOffline'
  | 'safety.report.reason.danger'
  | 'safety.report.reason.ghost_event'
  | 'safety.report.reason.harassment'
  | 'safety.report.reason.hate'
  | 'safety.report.reason.illegal'
  | 'safety.report.reason.impersonation'
  | 'safety.report.reason.other'
  | 'safety.report.reason.privacy'
  | 'safety.report.reason.scam'
  | 'safety.report.reason.sexual'
  | 'safety.report.reason.spam'
  | 'safety.report.reason.unsafe_setup'
  | 'safety.report.reasonLabel'
  | 'safety.report.reassurance'
  | 'safety.report.submit'
  | 'safety.report.submitted'
  | 'safety.report.submittedBody'
  | 'safety.report.submitting'
  | 'safety.report.title.comment'
  | 'safety.report.title.event'
  | 'safety.report.title.post'
  | 'safety.report.title.user'
  | 'shell.a11y.bottomNav'
  | 'shell.a11y.create'
  | 'shell.a11y.primaryNav'
  | 'shell.nav.create'
  | 'shell.nav.createEvent'
  | 'shell.nav.discover'
  | 'shell.nav.home'
  | 'shell.nav.myEvents'
  | 'shell.nav.notifications'
  | 'shell.nav.profile'
  | 'shell.rail.areas'
  | 'shell.rail.follow'
  | 'shell.rail.suggestions'
  | 'shell.rail.upcoming'
  | 'theme.dark'
  | 'theme.light'
  | 'theme.system'
  | 'trust.badge.aria'
  | 'trust.badge.short'
  | 'trust.level.t0'
  | 'trust.level.t1'
  | 'trust.level.t2'
  | 'trust.level.t3'
  | 'trust.level.t4'
  | 'trust.level.t5'
  | 'trust.requirement.accountAge7d'
  | 'trust.requirement.attend10Events'
  | 'trust.requirement.attend5Events'
  | 'trust.requirement.attendFirstEvent'
  | 'trust.requirement.host5Events'
  | 'trust.requirement.hostFirstEvent'
  | 'trust.requirement.resolveReports'
  | 'trust.requirement.verifyContact';

export const MESSAGE_KEYS = [
  'a11y.clearFilter',
  'a11y.closeMenu',
  'a11y.openMenu',
  'a11y.switchLanguage',
  'a11y.toggleTheme',
  'admin.audit.action.content_hidden',
  'admin.audit.action.content_restored',
  'admin.audit.action.event_restored',
  'admin.audit.action.event_suspended',
  'admin.audit.action.event_taken_down',
  'admin.audit.action.report_dismissed',
  'admin.audit.action.severity_changed',
  'admin.audit.action.user_suspended',
  'admin.audit.action.user_unsuspended',
  'admin.audit.column.action',
  'admin.audit.column.actor',
  'admin.audit.column.change',
  'admin.audit.column.entity',
  'admin.audit.column.reason',
  'admin.audit.column.time',
  'admin.audit.empty',
  'admin.audit.entityType.comment',
  'admin.audit.entityType.event',
  'admin.audit.entityType.moderation_ticket',
  'admin.audit.entityType.post',
  'admin.audit.entityType.user',
  'admin.audit.error.title',
  'admin.audit.filter.action',
  'admin.audit.filter.actor',
  'admin.audit.filter.any',
  'admin.audit.filter.apply',
  'admin.audit.filter.entityType',
  'admin.audit.filter.from',
  'admin.audit.filter.reset',
  'admin.audit.filter.to',
  'admin.audit.loadMore',
  'admin.audit.readOnly',
  'admin.audit.severity.critical',
  'admin.audit.severity.info',
  'admin.audit.severity.notice',
  'admin.audit.severity.warning',
  'admin.audit.system',
  'admin.audit.title',
  'admin.header.signedInAs',
  'admin.health.checkedAt',
  'admin.health.dependency.database',
  'admin.health.dependency.redisCache',
  'admin.health.dependency.redisQueue',
  'admin.health.dependencyStatus.down',
  'admin.health.dependencyStatus.up',
  'admin.health.environmentLabel',
  'admin.health.state.allUp.body',
  'admin.health.state.allUp.title',
  'admin.health.state.degraded.body',
  'admin.health.state.degraded.title',
  'admin.health.state.unreachable.body',
  'admin.health.state.unreachable.title',
  'admin.health.title',
  'admin.health.uptimeLabel',
  'admin.login.body',
  'admin.login.rejected',
  'admin.login.title',
  'admin.moderation.action.changeSeverity',
  'admin.moderation.action.dismiss',
  'admin.moderation.action.hide_content',
  'admin.moderation.action.restore_content',
  'admin.moderation.action.restore_event',
  'admin.moderation.action.suspend_event',
  'admin.moderation.action.suspend_user',
  'admin.moderation.action.take_down_event',
  'admin.moderation.action.unsuspend_user',
  'admin.moderation.actionType.content_hidden',
  'admin.moderation.actionType.content_restored',
  'admin.moderation.actionType.event_restored',
  'admin.moderation.actionType.event_suspended',
  'admin.moderation.actionType.event_taken_down',
  'admin.moderation.actionType.no_action',
  'admin.moderation.actionType.severity_changed',
  'admin.moderation.actionType.user_suspended',
  'admin.moderation.actionType.user_unsuspended',
  'admin.moderation.form.cancel',
  'admin.moderation.form.duration',
  'admin.moderation.form.durationHint',
  'admin.moderation.form.errorGeneric',
  'admin.moderation.form.note',
  'admin.moderation.form.noteCounter',
  'admin.moderation.form.reason',
  'admin.moderation.form.severity',
  'admin.moderation.form.submit',
  'admin.moderation.form.submitting',
  'admin.moderation.queue.column.closedAt',
  'admin.moderation.queue.column.firstReported',
  'admin.moderation.queue.column.outcome',
  'admin.moderation.queue.column.reasons',
  'admin.moderation.queue.column.reports',
  'admin.moderation.queue.column.severity',
  'admin.moderation.queue.column.sla',
  'admin.moderation.queue.column.target',
  'admin.moderation.queue.empty.closed',
  'admin.moderation.queue.empty.open',
  'admin.moderation.queue.error.body',
  'admin.moderation.queue.error.title',
  'admin.moderation.queue.filter.allSeverities',
  'admin.moderation.queue.filter.closed',
  'admin.moderation.queue.filter.open',
  'admin.moderation.queue.loadMore',
  'admin.moderation.queue.title',
  'admin.moderation.severity.critical',
  'admin.moderation.severity.high',
  'admin.moderation.severity.low',
  'admin.moderation.severity.normal',
  'admin.moderation.sla.dueSoon',
  'admin.moderation.sla.normal',
  'admin.moderation.sla.overdue',
  'admin.moderation.sla.stopped',
  'admin.moderation.targetType.comment',
  'admin.moderation.targetType.event',
  'admin.moderation.targetType.post',
  'admin.moderation.targetType.user',
  'admin.moderation.ticket.actorSystem',
  'admin.moderation.ticket.addAction',
  'admin.moderation.ticket.back',
  'admin.moderation.ticket.currentStatus',
  'admin.moderation.ticket.error.title',
  'admin.moderation.ticket.historyEmpty',
  'admin.moderation.ticket.historyTitle',
  'admin.moderation.ticket.noDescription',
  'admin.moderation.ticket.owner',
  'admin.moderation.ticket.reporter',
  'admin.moderation.ticket.reporterDeleted',
  'admin.moderation.ticket.reportsTitle',
  'admin.moderation.ticket.snapshotTitle',
  'admin.moderation.ticket.suspendedUntil',
  'admin.moderation.ticket.targetDeleted',
  'admin.moderation.ticketStatus.dismissed',
  'admin.moderation.ticketStatus.open',
  'admin.moderation.ticketStatus.resolved',
  'admin.nav.auditLog',
  'admin.nav.moderationQueue',
  'admin.nav.overview',
  'admin.nav.systemHealth',
  'admin.overview.body',
  'admin.overview.title',
  'area.all',
  'area.eventCount',
  'area.label',
  'auth.action.signIn',
  'auth.action.signOut',
  'auth.action.signUp',
  'auth.action.working',
  'auth.error.generic',
  'auth.error.offline',
  'auth.field.displayName',
  'auth.field.email',
  'auth.field.handle',
  'auth.field.identifier',
  'auth.field.password',
  'auth.hint.handle',
  'auth.hint.identifier',
  'auth.hint.password',
  'auth.page.signInBody',
  'auth.page.signInTitle',
  'auth.page.signUpBody',
  'auth.page.signUpTitle',
  'auth.prompt.body',
  'auth.prompt.title',
  'auth.switch.haveAccount',
  'auth.switch.noAccount',
  'blank.backHome',
  'blank.createEvent.body',
  'blank.createEvent.title',
  'blank.discover.body',
  'blank.discover.title',
  'blank.myEvents.body',
  'blank.myEvents.title',
  'blank.notFound.body',
  'blank.notFound.title',
  'blank.notifications.body',
  'blank.notifications.title',
  'common.appName',
  'common.comingSoon',
  'common.free',
  'common.language',
  'common.loading',
  'common.retry',
  'common.seeAll',
  'common.skipToContent',
  'datetime.timeZoneNote',
  'datetime.today',
  'datetime.tomorrow',
  'discover.areas.aria',
  'discover.areas.heading',
  'discover.category.language',
  'discover.category.outdoors',
  'discover.category.social',
  'discover.category.sports',
  'discover.category.wellness',
  'discover.empty.clear',
  'discover.empty.description',
  'discover.empty.title',
  'discover.filters.activeCount',
  'discover.filters.button',
  'discover.filters.category',
  'discover.filters.clear',
  'discover.filters.close',
  'discover.filters.done',
  'discover.filters.freeOnly',
  'discover.filters.title',
  'discover.map.aria',
  'discover.map.markerAria',
  'discover.map.placeholderNote',
  'discover.map.title',
  'discover.results.count',
  'discover.search.label',
  'discover.search.placeholder',
  'discover.title',
  'discover.view.label',
  'discover.view.list',
  'discover.view.map',
  'errors.area.notFound',
  'errors.area.outsideCoverage',
  'errors.auth.accountSuspended',
  'errors.auth.accountUnavailable',
  'errors.auth.emailTaken',
  'errors.auth.handleFormat',
  'errors.auth.handleTaken',
  'errors.auth.invalidCredentials',
  'errors.auth.invalidRefresh',
  'errors.auth.invalidToken',
  'errors.auth.roleNotAllowed',
  'errors.auth.trustLevelTooLow',
  'errors.auth.unauthenticated',
  'errors.block.selfNotAllowed',
  'errors.chat.cannotMessageSelf',
  'errors.chat.conversationClosed',
  'errors.chat.conversationNotFound',
  'errors.chat.messageNotFound',
  'errors.chat.messagePayloadMismatch',
  'errors.chat.notRequestRecipient',
  'errors.chat.requestQuotaExhausted',
  'errors.chat.requestRefused',
  'errors.comment.cannotPinReply',
  'errors.comment.notAuthor',
  'errors.comment.notFound',
  'errors.comment.notThreadOwner',
  'errors.comment.parentNotFound',
  'errors.common.constraintViolated',
  'errors.common.duplicate',
  'errors.common.idempotencyKeyRequired',
  'errors.common.referenceNotFound',
  'errors.common.retryLater',
  'errors.content.underModeration',
  'errors.event.notFound',
  'errors.event.notOrganizer',
  'errors.event.radiusRequiresCoordinates',
  'errors.event.underModeration',
  'errors.media.notFound',
  'errors.media.notUploaded',
  'errors.media.tooLarge',
  'errors.media.typeNotAllowed',
  'errors.moderation.conflictOfInterest',
  'errors.moderation.invalidState',
  'errors.moderation.noteTooLong',
  'errors.moderation.noteTooShort',
  'errors.moderation.reasonRequired',
  'errors.moderation.selfNotAllowed',
  'errors.moderation.suspensionTooLong',
  'errors.moderation.targetNotFound',
  'errors.moderation.targetNotInTicket',
  'errors.moderation.targetProtected',
  'errors.moderation.ticketAlreadyClosed',
  'errors.moderation.ticketNotFound',
  'errors.post.notFound',
  'errors.post.notOwner',
  'errors.profile.notFound',
  'errors.profile.phoneInvalid',
  'errors.profile.phoneTaken',
  'errors.report.descriptionTooLong',
  'errors.report.rateLimited',
  'errors.report.selfNotAllowed',
  'errors.report.targetNotFound',
  'event.card.almostFull',
  'event.card.attendees',
  'event.card.details',
  'event.card.hostedBy',
  'event.card.price',
  'event.card.startingSoon',
  'event.card.yours',
  'event.create.error',
  'event.create.field.area',
  'event.create.field.capacity',
  'event.create.field.description',
  'event.create.field.location',
  'event.create.field.startsAt',
  'event.create.field.title',
  'event.create.hint.capacity',
  'event.create.hint.description',
  'event.create.publish',
  'event.create.saveDraft',
  'event.create.title',
  'event.create.working',
  'event.detail.attendees',
  'event.detail.attendeesEmpty',
  'event.detail.attendeesSignedOut',
  'event.detail.full',
  'event.detail.hostedBy',
  'event.detail.joinWaitlistButton',
  'event.detail.missingBody',
  'event.detail.missingTitle',
  'event.detail.publish',
  'event.detail.rsvpButton',
  'event.detail.seatsLeft',
  'event.empty.cta',
  'event.empty.description',
  'event.empty.resetFilter',
  'event.empty.title',
  'event.requiredTrust',
  'event.status.cancelled',
  'event.status.draft',
  'event.status.pendingReview',
  'event.status.pending_review',
  'event.status.published',
  'event.status.suspended',
  'event.status.takenDown',
  'event.status.taken_down',
  'feed.activity.joinedMany',
  'feed.activity.joinedOne',
  'feed.activityJoined',
  'feed.card.comments',
  'feed.card.createdEvent',
  'feed.card.full',
  'feed.card.going',
  'feed.card.join',
  'feed.card.joined',
  'feed.card.menu',
  'feed.card.openEvent',
  'feed.card.seatsLeft',
  'feed.card.share',
  'feed.clearFilter',
  'feed.comments',
  'feed.composer.create',
  'feed.composer.placeholder',
  'feed.composerPlaceholder',
  'feed.createEvent',
  'feed.createdEvent',
  'feed.curatedEvent',
  'feed.empty.description',
  'feed.empty.reset',
  'feed.empty.title',
  'feed.emptyBody',
  'feed.emptyTitle',
  'feed.filter.all',
  'feed.filter.free',
  'feed.filter.label',
  'feed.filter.today',
  'feed.filter.weekend',
  'feed.filterAll',
  'feed.filterFree',
  'feed.filterToday',
  'feed.filterWeekend',
  'feed.going',
  'feed.joinWaitlist',
  'feed.loading',
  'feed.moreActions',
  'feed.onWaitlist',
  'feed.plusOthers',
  'feed.rsvp',
  'feed.seatsOf',
  'feed.share',
  'feed.title',
  'home.componentsHeading',
  'home.componentsNote',
  'home.eyebrow',
  'home.route.areas',
  'home.route.areasDescription',
  'home.route.detail',
  'home.route.detailDescription',
  'home.route.feed',
  'home.route.feedDescription',
  'home.route.profile',
  'home.route.profileDescription',
  'home.routesHeading',
  'home.routesNote',
  'home.status.planned',
  'home.status.ready',
  'home.subtitle',
  'home.title',
  'nav.createEvent',
  'nav.events',
  'nav.map',
  'nav.profile',
  'post.card.cityWide',
  'post.card.comments',
  'post.card.edited',
  'post.card.gallery',
  'post.card.posted',
  'post.card.react',
  'post.card.showMore',
  'post.composer.areaCityWide',
  'post.composer.areaLabel',
  'post.composer.back',
  'post.composer.bodyLabel',
  'post.composer.bodyPlaceholder',
  'post.composer.cancel',
  'post.composer.errorGeneric',
  'post.composer.errorOffline',
  'post.composer.kindLabel',
  'post.composer.open',
  'post.composer.remaining',
  'post.composer.skipMedia',
  'post.composer.submit',
  'post.composer.submitting',
  'post.composer.title',
  'post.composer.waitingUploads',
  'post.composer.you',
  'post.feed.empty',
  'post.feed.loading',
  'post.kind.lookingFor',
  'post.kind.notice',
  'post.kind.question',
  'post.kind.recommendation',
  'post.location.add',
  'post.location.labelField',
  'post.location.mapUnavailable',
  'post.location.pinned',
  'post.location.remove',
  'post.location.tapToPin',
  'post.media.addMore',
  'post.media.choose',
  'post.media.counter',
  'post.media.dropHint',
  'post.media.dropTitle',
  'post.media.next',
  'post.media.previewLabel',
  'post.media.previous',
  'post.media.rejectedSize',
  'post.media.rejectedType',
  'post.media.remove',
  'profile.action.cancel',
  'profile.action.edit',
  'profile.action.save',
  'profile.action.saving',
  'profile.error.save',
  'profile.field.bio',
  'profile.field.displayName',
  'profile.field.headline',
  'profile.field.homeArea',
  'profile.field.memberSince',
  'profile.field.noArea',
  'profile.field.phone',
  'profile.field.showArea',
  'profile.field.since',
  'profile.field.visibility',
  'profile.hint.headline',
  'profile.hint.phone',
  'profile.language.de',
  'profile.language.en',
  'profile.language.es',
  'profile.language.fr',
  'profile.language.ja',
  'profile.language.ko',
  'profile.language.other',
  'profile.language.ru',
  'profile.language.vi',
  'profile.language.zh',
  'profile.level.basic',
  'profile.level.conversational',
  'profile.level.fluent',
  'profile.level.native',
  'profile.missing.body',
  'profile.missing.title',
  'profile.section.about',
  'profile.stat.attended',
  'profile.stat.hosted',
  'profile.stat.rating',
  'profile.trust.next',
  'profile.visibility.members_only',
  'profile.visibility.private',
  'profile.visibility.public',
  'profile.visibilityHint.members_only',
  'profile.visibilityHint.private',
  'profile.visibilityHint.public',
  'role.admin.label',
  'role.curator.label',
  'role.moderator.label',
  'role.superAdmin.label',
  'rsvp.action.working',
  'rsvp.error.alreadyRsvped',
  'rsvp.error.generic',
  'rsvp.error.idempotencyKeyRequired',
  'rsvp.error.notRegistered',
  'rsvp.error.occurrenceClosed',
  'rsvp.error.occurrenceNotFound',
  'rsvp.error.suspended',
  'rsvp.error.trustTooLow',
  'safety.block.action',
  'safety.block.actionAuthor',
  'safety.block.actionOrganizer',
  'safety.block.blocked',
  'safety.block.cancel',
  'safety.block.confirm',
  'safety.block.confirmBody',
  'safety.block.confirmTitle',
  'safety.block.error',
  'safety.block.list.blockedAt',
  'safety.block.list.empty',
  'safety.block.list.title',
  'safety.block.unblock',
  'safety.block.working',
  'safety.label.contentHidden',
  'safety.label.eventSuspended',
  'safety.label.eventTakenDown',
  'safety.label.eventUnavailable',
  'safety.menu.more',
  'safety.report.action',
  'safety.report.alsoBlock',
  'safety.report.close',
  'safety.report.descriptionCounter',
  'safety.report.descriptionLabel',
  'safety.report.emergency_first',
  'safety.report.errorGeneric',
  'safety.report.errorOffline',
  'safety.report.reason.danger',
  'safety.report.reason.ghost_event',
  'safety.report.reason.harassment',
  'safety.report.reason.hate',
  'safety.report.reason.illegal',
  'safety.report.reason.impersonation',
  'safety.report.reason.other',
  'safety.report.reason.privacy',
  'safety.report.reason.scam',
  'safety.report.reason.sexual',
  'safety.report.reason.spam',
  'safety.report.reason.unsafe_setup',
  'safety.report.reasonLabel',
  'safety.report.reassurance',
  'safety.report.submit',
  'safety.report.submitted',
  'safety.report.submittedBody',
  'safety.report.submitting',
  'safety.report.title.comment',
  'safety.report.title.event',
  'safety.report.title.post',
  'safety.report.title.user',
  'shell.a11y.bottomNav',
  'shell.a11y.create',
  'shell.a11y.primaryNav',
  'shell.nav.create',
  'shell.nav.createEvent',
  'shell.nav.discover',
  'shell.nav.home',
  'shell.nav.myEvents',
  'shell.nav.notifications',
  'shell.nav.profile',
  'shell.rail.areas',
  'shell.rail.follow',
  'shell.rail.suggestions',
  'shell.rail.upcoming',
  'theme.dark',
  'theme.light',
  'theme.system',
  'trust.badge.aria',
  'trust.badge.short',
  'trust.level.t0',
  'trust.level.t1',
  'trust.level.t2',
  'trust.level.t3',
  'trust.level.t4',
  'trust.level.t5',
  'trust.requirement.accountAge7d',
  'trust.requirement.attend10Events',
  'trust.requirement.attend5Events',
  'trust.requirement.attendFirstEvent',
  'trust.requirement.host5Events',
  'trust.requirement.hostFirstEvent',
  'trust.requirement.resolveReports',
  'trust.requirement.verifyContact',
] as const;
